
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/google/gopacket"
  version = "1.1.12"

[[constraint]]
  name = "github.com/pilosa/go-pilosa"
  branch = "use-schema-endpoint-instead-of-status"
  source = "github.com/yuce/go-pilosa"

[[constraint]]
  name = "github.com/pilosa/pilosa"
  branch = "cluster-resize"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "=1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "=1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"
