version: 2
defaults: &defaults
  working_directory: /go/src/github.com/pilosa/pdk
  docker:
    - image: circleci/golang:1.12
  environment:
    GO111MODULE: "on"
fast-checkout: &fast-checkout
  attach_workspace:
    at: .
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - mod-cache-{{ checksum "go.sum" }}
      - run: "go mod download"
      - save_cache:
          key: mod-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod/
      - persist_to_workspace:
          root: .
          paths: "*"
  linter:
    <<: *defaults
    steps:
      - *fast-checkout
      - run: make install-gometalinter
      - run: make gometalinter
  test-golang-1.12: &base-test
    <<: *defaults
    steps:
      - *fast-checkout
      - run: make test
  test-golang-1.13:
    <<: *base-test
    docker:
      - image: circleci/golang:1.13
workflows:
  version: 2
  test:
    jobs:
      - build
      - linter:
          requires:
            - build
      - test-golang-1.12:
          requires:
            - build
      - test-golang-1.13:
          requires:
            - build
